sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t tyrelfecha/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true tyrelfecha/react-test npm test
    
after_success:
    - docker build -t tyrelfecha/multi-client -f ./client
    - docker build -t tyrelfecha/multi-nginx -f ./nginx
    - docker build -t tyrelfecha/multi-server -f ./server
    - docker build -t tyrelfecha/multi-worker -f ./worker
    # login to docker CLI
    - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
    # Take imagegs push to Docker Hub
    - docker push tyrelfecha/multi-client
    - docker push tyrelfecha/multi-nginx
    - docker push tyrelfecha/multi-server
    - docker push tyrelfecha/multi-worker